export const BLOOD_REQUESTS_REQUEST = 'BLOOD_REQUESTS_REQUEST';
export const BLOOD_REQUESTS_SUCCESS = 'BLOOD_REQUESTS_SUCCESS';
export const BLOOD_REQUESTS_FAIL = 'BLOOD_REQUESTS_FAIL';

export const BLOOD_REQUEST_DETAIL_REQUEST = 'BLOOD_REQUEST_DETAIL_REQUEST';
export const BLOOD_REQUEST_DETAIL_SUCCESS = 'BLOOD_REQUEST_DETAIL_SUCCESS';
export const BLOOD_REQUEST_DETAIL_FAIL = 'BLOOD_REQUEST_DETAIL_FAIL';

export const BLOOD_REQUEST_SEARCH_REQUEST = 'BLOOD_REQUEST_SEARCH_REQUEST';
export const BLOOD_REQUEST_SEARCH_SUCCESS = 'BLOOD_REQUEST_SEARCH_SUCCESS';
export const BLOOD_REQUEST_SEARCH_FAIL = 'BLOOD_REQUEST_SEARCH_FAIL';

export const BLOOD_DONATION_EVENTS_REQUEST = 'BLOOD_DONATION_EVENTS_REQUEST';
export const BLOOD_DONATION_EVENTS_SUCCESS = 'BLOOD_DONATION_EVENTS_SUCCESS';
export const BLOOD_DONATION_EVENTS_FAIL = 'BLOOD_DONATION_EVENTS_FAIL';

export const BLOOD_REQUEST_STATS_REQUEST = 'BLOOD_REQUEST_STATS_REQUEST';
export const BLOOD_REQUEST_STATS_SUCCESS = 'BLOOD_REQUEST_STATS_SUCCESS';
export const BLOOD_REQUEST_STATS_FAIL = 'BLOOD_REQUEST_STATS_FAIL';

export const BLOOD_REQUEST_LIST_REQUEST = 'BLOOD_REQUEST_LIST_REQUEST';
export const BLOOD_REQUEST_LIST_SUCCESS = 'BLOOD_REQUEST_LIST_SUCCESS';
export const BLOOD_REQUEST_LIST_FAIL = 'BLOOD_REQUEST_LIST_FAIL';
export const BLOOD_REQUEST_LIST_RESET = 'BLOOD_REQUEST_LIST_RESET';

export const BLOOD_REQUEST_DETAILS_REQUEST = 'BLOOD_REQUEST_DETAILS_REQUEST';
export const BLOOD_REQUEST_DETAILS_SUCCESS = 'BLOOD_REQUEST_DETAILS_SUCCESS';
export const BLOOD_REQUEST_DETAILS_FAIL = 'BLOOD_REQUEST_DETAILS_FAIL';
export const BLOOD_REQUEST_DETAILS_RESET = 'BLOOD_REQUEST_DETAILS_RESET'; 