export const DONOR_PROFILE_REQUEST = 'DONOR_PROFILE_REQUEST';
export const DONOR_PROFILE_SUCCESS = 'DONOR_PROFILE_SUCCESS';
export const DONOR_PROFILE_FAIL = 'DONOR_PROFILE_FAIL';
export const DONOR_PROFILE_RESET = 'DONOR_PROFILE_RESET';

export const DONOR_UPDATE_PROFILE_REQUEST = 'DONOR_UPDATE_PROFILE_REQUEST';
export const DONOR_UPDATE_PROFILE_SUCCESS = 'DONOR_UPDATE_PROFILE_SUCCESS';
export const DONOR_UPDATE_PROFILE_FAIL = 'DONOR_UPDATE_PROFILE_FAIL';
export const DONOR_UPDATE_PROFILE_RESET = 'DONOR_UPDATE_PROFILE_RESET';

export const DONOR_ELIGIBLE_REQUESTS_REQUEST = 'DONOR_ELIGIBLE_REQUESTS_REQUEST';
export const DONOR_ELIGIBLE_REQUESTS_SUCCESS = 'DONOR_ELIGIBLE_REQUESTS_SUCCESS';
export const DONOR_ELIGIBLE_REQUESTS_FAIL = 'DONOR_ELIGIBLE_REQUESTS_FAIL';
export const DONOR_ELIGIBLE_REQUESTS_RESET = 'DONOR_ELIGIBLE_REQUESTS_RESET';

export const DONOR_RESPOND_REQUEST = 'DONOR_RESPOND_REQUEST';
export const DONOR_RESPOND_SUCCESS = 'DONOR_RESPOND_SUCCESS';
export const DONOR_RESPOND_FAIL = 'DONOR_RESPOND_FAIL';
export const DONOR_RESPOND_RESET = 'DONOR_RESPOND_RESET';

export const DONOR_HISTORY_REQUEST = 'DONOR_HISTORY_REQUEST';
export const DONOR_HISTORY_SUCCESS = 'DONOR_HISTORY_SUCCESS';
export const DONOR_HISTORY_FAIL = 'DONOR_HISTORY_FAIL';
export const DONOR_HISTORY_RESET = 'DONOR_HISTORY_RESET'; 