export const INSTITUTION_PROFILE_REQUEST = 'INSTITUTION_PROFILE_REQUEST';
export const INSTITUTION_PROFILE_SUCCESS = 'INSTITUTION_PROFILE_SUCCESS';
export const INSTITUTION_PROFILE_FAIL = 'INSTITUTION_PROFILE_FAIL';
export const INSTITUTION_PROFILE_RESET = 'INSTITUTION_PROFILE_RESET';

export const INSTITUTION_UPDATE_PROFILE_REQUEST = 'INSTITUTION_UPDATE_PROFILE_REQUEST';
export const INSTITUTION_UPDATE_PROFILE_SUCCESS = 'INSTITUTION_UPDATE_PROFILE_SUCCESS';
export const INSTITUTION_UPDATE_PROFILE_FAIL = 'INSTITUTION_UPDATE_PROFILE_FAIL';
export const INSTITUTION_UPDATE_PROFILE_RESET = 'INSTITUTION_UPDATE_PROFILE_RESET';

export const INSTITUTION_BLOOD_REQUESTS_REQUEST = 'INSTITUTION_BLOOD_REQUESTS_REQUEST';
export const INSTITUTION_BLOOD_REQUESTS_SUCCESS = 'INSTITUTION_BLOOD_REQUESTS_SUCCESS';
export const INSTITUTION_BLOOD_REQUESTS_FAIL = 'INSTITUTION_BLOOD_REQUESTS_FAIL';
export const INSTITUTION_BLOOD_REQUESTS_RESET = 'INSTITUTION_BLOOD_REQUESTS_RESET';

export const BLOOD_REQUEST_CREATE_REQUEST = 'BLOOD_REQUEST_CREATE_REQUEST';
export const BLOOD_REQUEST_CREATE_SUCCESS = 'BLOOD_REQUEST_CREATE_SUCCESS';
export const BLOOD_REQUEST_CREATE_FAIL = 'BLOOD_REQUEST_CREATE_FAIL';
export const BLOOD_REQUEST_CREATE_RESET = 'BLOOD_REQUEST_CREATE_RESET';

export const BLOOD_REQUEST_UPDATE_REQUEST = 'BLOOD_REQUEST_UPDATE_REQUEST';
export const BLOOD_REQUEST_UPDATE_SUCCESS = 'BLOOD_REQUEST_UPDATE_SUCCESS';
export const BLOOD_REQUEST_UPDATE_FAIL = 'BLOOD_REQUEST_UPDATE_FAIL';
export const BLOOD_REQUEST_UPDATE_RESET = 'BLOOD_REQUEST_UPDATE_RESET';

export const BLOOD_REQUEST_DELETE_REQUEST = 'BLOOD_REQUEST_DELETE_REQUEST';
export const BLOOD_REQUEST_DELETE_SUCCESS = 'BLOOD_REQUEST_DELETE_SUCCESS';
export const BLOOD_REQUEST_DELETE_FAIL = 'BLOOD_REQUEST_DELETE_FAIL';
export const BLOOD_REQUEST_DELETE_RESET = 'BLOOD_REQUEST_DELETE_RESET';

export const BLOOD_REQUEST_DETAILS_REQUEST = 'BLOOD_REQUEST_DETAILS_REQUEST';
export const BLOOD_REQUEST_DETAILS_SUCCESS = 'BLOOD_REQUEST_DETAILS_SUCCESS';
export const BLOOD_REQUEST_DETAILS_FAIL = 'BLOOD_REQUEST_DETAILS_FAIL';
export const BLOOD_REQUEST_DETAILS_RESET = 'BLOOD_REQUEST_DETAILS_RESET';

export const INSTITUTION_UPDATE_BLOOD_REQUEST_RESET = 'INSTITUTION_UPDATE_BLOOD_REQUEST_RESET';

export const DONOR_APPOINTMENT_CONFIRM_REQUEST = 'DONOR_APPOINTMENT_CONFIRM_REQUEST';
export const DONOR_APPOINTMENT_CONFIRM_SUCCESS = 'DONOR_APPOINTMENT_CONFIRM_SUCCESS';
export const DONOR_APPOINTMENT_CONFIRM_FAIL = 'DONOR_APPOINTMENT_CONFIRM_FAIL';
export const DONOR_APPOINTMENT_CONFIRM_RESET = 'DONOR_APPOINTMENT_CONFIRM_RESET';

export const DONATION_COMPLETE_REQUEST = 'DONATION_COMPLETE_REQUEST';
export const DONATION_COMPLETE_SUCCESS = 'DONATION_COMPLETE_SUCCESS';
export const DONATION_COMPLETE_FAIL = 'DONATION_COMPLETE_FAIL';
export const DONATION_COMPLETE_RESET = 'DONATION_COMPLETE_RESET'; 